import { useState, useEffect } from "react";
import { BrowserRouter as Router, Routes, Route, Link } from "react-router-dom";
import "./index.css";
import "./App.css";

function App() {
  const [currentPage, setCurrentPage] = useState("ai");
  const [theme, setTheme] = useState("dark");
  const [aiPrompt, setAiPrompt] = useState("");
  const [trackerInput, setTrackerInput] = useState("");
  const [response, setResponse] = useState("");
  const [loading, setLoading] = useState(false);
  const [snippets, setSnippets] = useState([]);
  const [snippetName, setSnippetName] = useState("");
  const [trackerTopics, setTrackerTopics] = useState([]);
  const [currentTopicStatus, setCurrentTopicStatus] = useState("pending");

  // Load data
  /* eslint-disable react-hooks/set-state-in-effect */
  useEffect(() => {
    const snippetsSaved = localStorage.getItem("codeSnippets");
    const trackerSaved = localStorage.getItem("learningTracker");
    if (snippetsSaved) setSnippets(JSON.parse(snippetsSaved));
    if (trackerSaved) setTrackerTopics(JSON.parse(trackerSaved));
    const savedTheme = localStorage.getItem("theme");
    if (savedTheme) {
      setTheme(savedTheme);
      document.body.dataset.theme = savedTheme;
    }
  }, []);
  /* eslint-enable react-hooks/set-state-in-effect */

  // Save snippets
  useEffect(() => {
    localStorage.setItem("codeSnippets", JSON.stringify(snippets));
  }, [snippets]);

  // Save tracker
  useEffect(() => {
    localStorage.setItem("learningTracker", JSON.stringify(trackerTopics));
  }, [trackerTopics]);

  // Save theme
  useEffect(() => {
    localStorage.setItem("theme", theme);
    document.body.dataset.theme = theme;
  }, [theme]);

  const handleSend = async () => {
    if (!aiPrompt.trim()) return;
    setLoading(true);
    setResponse("");
    await new Promise((resolve) => setTimeout(resolve, 1500));
    let generatedCode = "// AI Response\n\n";
    const lowerPrompt = aiPrompt.toLowerCase();
    if (lowerPrompt.includes("todo") || lowerPrompt.includes("task")) {
      generatedCode += `import { useState } from 'react';\n\nfunction TodoList() {\n  // full todo code\n}`;
    } else if (
      lowerPrompt.includes("react") ||
      lowerPrompt.includes("component")
    ) {
      generatedCode += `import React from 'react';\n\nconst MyComponent = () => <div>Hello</div>;\n\nexport default MyComponent;`;
    } else {
      generatedCode += `// Code for "${aiPrompt}"\nconsole.log('Sample output generated by NEXUS');`;
    }
    setResponse(generatedCode);
    setLoading(false);
  };

  const saveSnippet = () => {
    if (!snippetName.trim() || !response) {
      alert("Please provide a name for the snippet.");
      return;
    }
    const newSnippet = { id: Date.now(), name: snippetName, code: response };
    setSnippets([newSnippet, ...snippets]);
    setSnippetName("");
  };

  const deleteSnippet = (id) =>
    setSnippets(snippets.filter((s) => s.id !== id));

  const copyText = (text) => navigator.clipboard.writeText(text);

  const addTopic = () => {
    if (trackerInput.trim()) {
      setTrackerTopics([
        ...trackerTopics,
        {
          id: Date.now(),
          name: trackerInput.trim(),
          status: currentTopicStatus,
          notes: "",
          date: new Date().toLocaleDateString(),
          subTasks: [],
          progress: 0,
        },
      ]);
      setTrackerInput("");
    }
  };

  const updateTopicStatus = (id, status) => {
    setTrackerTopics(
      trackerTopics.map((t) => (t.id === id ? { ...t, status } : t)),
    );
  };

  const deleteTopic = (id) =>
    setTrackerTopics(trackerTopics.filter((t) => t.id !== id));

  const getStats = () => {
    const total = trackerTopics.length;
    const completed = trackerTopics.filter(
      (t) => t.status === "completed",
    ).length;
    const pending = trackerTopics.filter((t) => t.status === "pending").length;
    const incomplete = trackerTopics.filter(
      (t) => t.status === "incomplete",
    ).length;
    return {
      total,
      completed,
      pending,
      incomplete,
      overallProgress: total ? Math.round((completed / total) * 100) : 0,
    };
  };

  const clearData = () => {
    if (confirm("Clear all data?")) {
      setSnippets([]);
      setTrackerTopics([]);
      localStorage.clear();
    }
  };

  const exportData = () => {
    const data = { snippets, tracker: trackerTopics };
    const blob = new Blob([JSON.stringify(data, null, 2)], {
      type: "application/json",
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "nexus-data.json";
    a.click();
  };

  const pageComponents = {
    ai: (
      <section className="page-content">
        <h2>🤖 AI Helper</h2>
        <div className="input-section">
          <textarea
            value={aiPrompt}
            onChange={(e) => setAiPrompt(e.target.value)}
            placeholder="Describe the component or function you need..."
            rows="4"
            disabled={loading}
          />
          <button onClick={handleSend} disabled={loading || !aiPrompt.trim()}>
            {loading ? "Generating..." : "Generate Code"}
          </button>
        </div>
        {response && (
          <div className="response-section">
            <pre className="code-block">
              <code>{response}</code>
            </pre>
            <div className="action-row">
              <input
                value={snippetName}
                onChange={(e) => setSnippetName(e.target.value)}
                placeholder="Snippet name"
              />
              <button className="secondary" onClick={() => copyText(response)}>
                Copy
              </button>
              <button
                onClick={saveSnippet}
                disabled={!snippetName.trim()}
                className="primary"
              >
                Save Snippet
              </button>
            </div>
          </div>
        )}
      </section>
    ),
    snippets: (
      <section className="page-content">
        <h2>💾 Snippets ({snippets.length})</h2>
        <div className="items-grid">
          {snippets.map((s) => (
            <div key={s.id} className="item-card">
              <h4>{s.name}</h4>
              <pre className="preview-code">
                <code>{s.code.slice(0, 150)}...</code>
              </pre>
              <div className="card-actions">
                <button onClick={() => copyText(s.code)}>Copy Code</button>
                <button className="danger" onClick={() => deleteSnippet(s.id)}>
                  Delete
                </button>
              </div>
            </div>
          ))}
        </div>
      </section>
    ),
    tracker: (
      <section className="page-content">
        <h2>📚 Learning Tracker</h2>
        <div className="dashboard">
          {(() => {
            const stats = getStats();
            return (
              <>
                <div className="stats-row">
                  <div className="stat-box pending">
                    <div className="stat-value">{stats.pending}</div>
                    <div>Pending</div>
                  </div>
                  <div className="stat-box incomplete">
                    <div className="stat-value">{stats.incomplete}</div>
                    <div>Incomplete</div>
                  </div>
                  <div className="stat-box completed">
                    <div className="stat-value">{stats.completed}</div>
                    <div>Completed</div>
                  </div>
                </div>
                <div className="progress-ring">
                  <svg viewBox="0 0 120 120">
                    <defs>
                      <linearGradient
                        id="progressGradient"
                        x1="0%"
                        y1="0%"
                        x2="100%"
                        y2="0%"
                      >
                        <stop offset="0%" stopColor="var(--accent)" />
                        <stop offset="100%" stopColor="var(--success)" />
                      </linearGradient>
                    </defs>
                    <circle
                      className="progress-bg"
                      cx="60"
                      cy="60"
                      r="52"
                    ></circle>
                    <circle
                      className="progress-fill"
                      cx="60"
                      cy="60"
                      r="52"
                      strokeDasharray="327"
                      strokeDashoffset={
                        327 - (327 * stats.overallProgress) / 100
                      }
                    ></circle>
                  </svg>
                  <div className="progress-text">
                    <div className="progress-num">{stats.overallProgress}%</div>
                    <div>Overall</div>
                  </div>
                </div>
              </>
            );
          })()}
        </div>
        <div className="add-row">
          <select
            value={currentTopicStatus}
            onChange={(e) => setCurrentTopicStatus(e.target.value)}
          >
            <option value="pending">Pending</option>
            <option value="incomplete">Incomplete</option>
            <option value="completed">Completed</option>
          </select>
          <input
            value={trackerInput}
            onChange={(e) => setTrackerInput(e.target.value)}
            placeholder="Add new topic"
          />
          <button onClick={addTopic}>Add Topic</button>
        </div>
        <div className="topics-list">
          {trackerTopics.map((t) => (
            <div key={t.id} className={`topic-card ${t.status}`}>
              <div className="topic-top">
                <h3>{t.name}</h3>
                <span className={`status-tag ${t.status}`}>
                  {t.status.toUpperCase()}
                </span>
              </div>
              <div className="topic-progress">
                <div className="progress-container">
                  <div className="progress-bar-bg">
                    <div
                      className="progress-bar-fill"
                      style={{ width: `${t.progress}%` }}
                    ></div>
                  </div>
                  <span>{t.progress}%</span>
                </div>
              </div>
              <div className="topic-actions">
                <button
                  onClick={() => updateTopicStatus(t.id, "pending")}
                  className={t.status === "pending" ? "active" : ""}
                >
                  Pending
                </button>
                <button
                  onClick={() => updateTopicStatus(t.id, "incomplete")}
                  className={t.status === "incomplete" ? "active" : ""}
                >
                  Incomplete
                </button>
                <button
                  onClick={() => updateTopicStatus(t.id, "completed")}
                  className={t.status === "completed" ? "active" : ""}
                >
                  Complete
                </button>
                <button
                  className="delete-btn"
                  onClick={() => deleteTopic(t.id)}
                >
                  Delete
                </button>
              </div>
            </div>
          ))}
          {trackerTopics.length === 0 && (
            <p className="empty-state">Add your first learning topic!</p>
          )}
        </div>
      </section>
    ),
    settings: (
      <section className="page-content">
        <h2>⚙️ Settings</h2>
        <div className="settings-list">
          <div className="setting-item">
            <label>Theme</label>
            <select value={theme} onChange={(e) => setTheme(e.target.value)}>
              <option value="dark">Dark</option>
              <option value="light">Light</option>
            </select>
          </div>
          <button className="danger" onClick={clearData}>
            Clear All Data
          </button>
          <button onClick={exportData}>Export Data (JSON)</button>
        </div>
      </section>
    ),
  };

  return (
    <div className="app">
      <header className="header">
        <h1>🚀 NEXUS</h1>
        <p>AI Code Helper | Snippets | Learning Tracker</p>
      </header>
      <div className="app-container">
        <aside className="sidebar">
          <nav>
            <button
              className={currentPage === "ai" ? "nav-active" : ""}
              onClick={() => setCurrentPage("ai")}
            >
              <span>🤖</span> AI Helper
            </button>
            <button
              className={currentPage === "snippets" ? "nav-active" : ""}
              onClick={() => setCurrentPage("snippets")}
            >
              <span>💾</span> Snippets
            </button>
            <button
              className={currentPage === "tracker" ? "nav-active" : ""}
              onClick={() => setCurrentPage("tracker")}
            >
              <span>📚</span> Learning Tracker
            </button>
            <button
              className={currentPage === "settings" ? "nav-active" : ""}
              onClick={() => setCurrentPage("settings")}
            >
              <span>⚙️</span> Settings
            </button>
          </nav>
        </aside>
        <main className="main-content">{pageComponents[currentPage]}</main>
      </div>
    </div>
  );
}

export default App;
